"""Add full-text search

Revision ID: 916b6f4fe353
Revises: 01ec60c94f68
Create Date: 2024-09-03 10:11:19.738182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "916b6f4fe353"
down_revision: Union[str, None] = "01ec60c94f68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index("ix_documents_text", table_name="documents")
    op.alter_column(
        "documents",
        "text",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.add_column(
        "documents",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('russian', text)", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_documents_search", "documents", ["search_vector"], postgresql_using="gin"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_documents_text", "documents", ["text"], unique=False)
    op.alter_column(
        "documents",
        "text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("documents", "search_vector")
    # ### end Alembic commands ###
