"""Add MD5 index for text

Revision ID: dbe65b087fb6
Revises: 916b6f4fe353
Create Date: 2024-09-03 13:30:55.288194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dbe65b087fb6"
down_revision: Union[str, None] = "916b6f4fe353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_search", table_name="documents", postgresql_using="gin")
    op.create_index(
        "ix_documents_text_md5",
        "documents",
        [sa.text("md5(text::text)")],
        unique=False,
        postgresql_using="btree",
    )
    op.drop_column("documents", "search_vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('russian'::regconfig, text)", persisted=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(
        "ix_documents_text_md5", table_name="documents", postgresql_using="btree"
    )
    op.create_index(
        "ix_documents_search",
        "documents",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
